Repository MAVRICK-1/Nest-Ondc, pull requests merged in 2024-06, with the labels that each got.

#22 footer updated
  src/components/footer/footer.js
Labels: ssoc, beginner

#31 Replace $ and Rs with ₹ symbol fix #20
  src/components/footer/footer.js
  src/components/product/index.js
  src/pages/Details/index.js
  src/pages/Home/TopProducts/index.js
  src/pages/cart/index.js
  src/pages/wishList/index.js
  yarn.lock
Labels: ssoc, beginner

#28 Added forgot password component and enabled signIn/forgotPassword buttons after selecting credentials from autosuggestion
  src/App.js
  src/pages/ForgotPassword/index.js
  src/pages/SignIn/index.js
  yarn.lock
Labels: ssoc, advanced

#48 updated #24 issue
  src/components/product/index.js
  src/components/product/style.css
Labels: ssoc, beginner

#42 Navigation Redirection Added - for #32
  src/components/header/nav/nav.js
Labels: ssoc, beginner

#49 remove "HTML Ecommerce Template" in Footer
  src/components/footer/footer.js
Labels: ssoc, beginner

#62 remove duplicate contact number
  src/components/footer/footer.js
Labels: ssoc, beginner

#59 open graph implementation and added site description #45
  public/index.html
  public/manifest.json
  public/nest-ondc-og.png
  yarn.lock
Labels: ssoc, intermediate

#68 Display Correct Discount percentage and commented all unused imports to reduce bundle size
  .eslintrc.js
  src/App.js
  src/components/Sidebar/index.js
  src/components/header/header.js
  src/components/product/index.js
  src/components/selectDrop/select.js
  src/firebase.js
  src/pages/Details/index.js
  src/pages/ForgotPassword/index.js
  src/pages/Home/TopProducts/index.js
  src/pages/Home/index.js
  src/pages/Home/slider/index.js
  src/pages/SignIn/index.js
  src/pages/SignUp/index.js
  src/pages/cart/index.js
  src/pages/wishList/index.js
Labels: ssoc, beginner

#74 Added feature so that only users with verified email can login and utilize the services.
  src/pages/SignIn/index.js
  src/pages/SignUp/index.js
Labels: ssoc, intermediate

#86 Update README.md
  README.md
Labels: ssoc, beginner

#88 Unresponsive Subscribe Newsletter Button on Carousel for Smaller Screens #43
  src/components/newsletter/style.css
  src/pages/Home/slider/index.css
  src/pages/Home/slider/index.js
  src/responsive.css
Labels: ssoc, intermediate

#93 Added a TnC Page and Fixed Footer Typo
  src/App.js
  src/components/footer/footer.js
  src/pages/Terms/index.js
  src/pages/Terms/style.css
Labels: ssoc, intermediate

#94 Added Redirection for My Wishlist button
  src/components/header/header.js
  yarn.lock
Labels: ssoc, beginner

#95 Redirection in Related Products Page
  src/pages/Details/index.js
Labels: ssoc, beginner

#107 Fixed layout issues
  src/pages/Home/slider/index.js
Labels: ssoc, beginner
